### ISSUE TITLE
SpeedForwarder (Read this)

### ISSUE THREAD

**Issue by lostdusty** [FastForwardTeam/FastForward#656]
<div align="center">
<h1> <img src="https://fastforward.team/img/branding.png" width="400" /> </h1>
<p> <h3> <strong> SpeedForwarder: A new Fast Forward structure </strong> </h3> </p>
<p align="center"><a href="https://nightly.link/FastForwardTeam/FastForward/workflows/main/manifest-v3"> <img alt="GitHub Workflow Status (with branch)" src="https://img.shields.io/github/actions/workflow/status/FastForwardTeam/FastForward/main.yml?branch=manifest-v3&style=for-the-badge"></a> </p>
</div>

****

# A new way to bypass
We, the developers of Fast Forward are working on a new update, and with this update, writing bypasses will be easier than never! And also, the so wanted whitelist feature will be added. Check back this issue to see any updates.

_During that big update, we won't take any new bypass requests, only fix broken bypasses._

## Milestone
Currently, our milestone is:

- [x] Redesign how the import_script is handled
- [x] Implement the new project structure
- [x] Add the whitelist feature
- [x] Test it both on Firefox and Chrome browsers
- [ ] See if theres any broken bypass due of the changes
- [ ] Update it on all 3 stores

**Comment by lostdusty** [comment]
In case you want to comment something about this (e.g. questions), you can use this discussion #657.
